language: generic

before_deploy:
  image: python:latest
  script:
    - pip install awscli
    - aws s3 rm s3://${BUCKET} --recursive

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$BUCKET"
  skip_cleanup: true
  local_dir: dist/portfolio
branches:
  only:
    - master
