language: python
python:
  - "3.6"

before_deploy: 
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws s3 rm s3://$BUCKET --recursive --region=$REGION

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$BUCKET"
  skip_cleanup: true
  local_dir: dist/portfolio
branches:
  only:
    - master
